/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 51
#define LARGE_STATE_COUNT 13
#define SYMBOL_COUNT 73
#define ALIAS_COUNT 0
#define TOKEN_COUNT 57
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 8
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  aux_sym__text_token1 = 2,
  aux_sym__not_token1 = 3,
  aux_sym__not_token2 = 4,
  aux_sym__not_token3 = 5,
  aux_sym__not_token4 = 6,
  sym_statement_begin = 7,
  sym_statement_end = 8,
  sym_expression_begin = 9,
  sym_expression_end = 10,
  anon_sym_LBRACE = 11,
  anon_sym_RBRACE = 12,
  anon_sym_LBRACE_POUND = 13,
  aux_sym_comment_token1 = 14,
  anon_sym_POUND_RBRACE = 15,
  anon_sym_for = 16,
  anon_sym_in = 17,
  anon_sym_endfor = 18,
  anon_sym_if = 19,
  anon_sym_and = 20,
  anon_sym_or = 21,
  anon_sym_endif = 22,
  anon_sym_else = 23,
  anon_sym_elif = 24,
  anon_sym_raw = 25,
  anon_sym_endraw = 26,
  anon_sym_macro = 27,
  anon_sym_endmacro = 28,
  anon_sym_extends = 29,
  anon_sym_block = 30,
  anon_sym_endblock = 31,
  anon_sym_call = 32,
  anon_sym_endcall = 33,
  anon_sym_filter = 34,
  anon_sym_endfilter = 35,
  anon_sym_set = 36,
  anon_sym_endset = 37,
  anon_sym_include = 38,
  anon_sym_import = 39,
  anon_sym_from = 40,
  anon_sym_autoescape = 41,
  anon_sym_endautoescape = 42,
  anon_sym_trans = 43,
  anon_sym_endtrans = 44,
  anon_sym_pluralize = 45,
  anon_sym_with = 46,
  anon_sym_endwith = 47,
  anon_sym_debug = 48,
  anon_sym_do = 49,
  anon_sym_is = 50,
  sym__white_space = 51,
  anon_sym_DOT = 52,
  sym_operator = 53,
  sym_filter_operator = 54,
  sym_equal_operator = 55,
  sym_string = 56,
  sym_source_file = 57,
  sym__text = 58,
  sym__not = 59,
  sym__node = 60,
  sym_statement = 61,
  sym_expression = 62,
  sym_map = 63,
  sym__map_begin = 64,
  sym__map_end = 65,
  sym_comment = 66,
  sym_keyword = 67,
  aux_sym__inner_text = 68,
  aux_sym__inner_text2 = 69,
  sym_dotted_identifier = 70,
  aux_sym_source_file_repeat1 = 71,
  aux_sym_dotted_identifier_repeat1 = 72,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [aux_sym__text_token1] = "_text_token1",
  [aux_sym__not_token1] = "_not_token1",
  [aux_sym__not_token2] = "_not_token2",
  [aux_sym__not_token3] = "_not_token3",
  [aux_sym__not_token4] = "_not_token4",
  [sym_statement_begin] = "statement_begin",
  [sym_statement_end] = "statement_end",
  [sym_expression_begin] = "expression_begin",
  [sym_expression_end] = "expression_end",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LBRACE_POUND] = "{#",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_POUND_RBRACE] = "#}",
  [anon_sym_for] = "for",
  [anon_sym_in] = "in",
  [anon_sym_endfor] = "endfor",
  [anon_sym_if] = "if",
  [anon_sym_and] = "and",
  [anon_sym_or] = "or",
  [anon_sym_endif] = "endif",
  [anon_sym_else] = "else",
  [anon_sym_elif] = "elif",
  [anon_sym_raw] = "raw",
  [anon_sym_endraw] = "endraw",
  [anon_sym_macro] = "macro",
  [anon_sym_endmacro] = "endmacro",
  [anon_sym_extends] = "extends",
  [anon_sym_block] = "block",
  [anon_sym_endblock] = "endblock",
  [anon_sym_call] = "call",
  [anon_sym_endcall] = "endcall",
  [anon_sym_filter] = "filter",
  [anon_sym_endfilter] = "endfilter",
  [anon_sym_set] = "set",
  [anon_sym_endset] = "endset",
  [anon_sym_include] = "include",
  [anon_sym_import] = "import",
  [anon_sym_from] = "from",
  [anon_sym_autoescape] = "autoescape",
  [anon_sym_endautoescape] = "endautoescape",
  [anon_sym_trans] = "trans",
  [anon_sym_endtrans] = "endtrans",
  [anon_sym_pluralize] = "pluralize",
  [anon_sym_with] = "with",
  [anon_sym_endwith] = "endwith",
  [anon_sym_debug] = "debug",
  [anon_sym_do] = "do",
  [anon_sym_is] = "is",
  [sym__white_space] = "_white_space",
  [anon_sym_DOT] = ".",
  [sym_operator] = "operator",
  [sym_filter_operator] = "filter_operator",
  [sym_equal_operator] = "equal_operator",
  [sym_string] = "string",
  [sym_source_file] = "source_file",
  [sym__text] = "_text",
  [sym__not] = "_not",
  [sym__node] = "_node",
  [sym_statement] = "statement",
  [sym_expression] = "expression",
  [sym_map] = "map",
  [sym__map_begin] = "_map_begin",
  [sym__map_end] = "_map_end",
  [sym_comment] = "comment",
  [sym_keyword] = "keyword",
  [aux_sym__inner_text] = "_inner_text",
  [aux_sym__inner_text2] = "_inner_text2",
  [sym_dotted_identifier] = "dotted_identifier",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_dotted_identifier_repeat1] = "dotted_identifier_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [aux_sym__text_token1] = aux_sym__text_token1,
  [aux_sym__not_token1] = aux_sym__not_token1,
  [aux_sym__not_token2] = aux_sym__not_token2,
  [aux_sym__not_token3] = aux_sym__not_token3,
  [aux_sym__not_token4] = aux_sym__not_token4,
  [sym_statement_begin] = sym_statement_begin,
  [sym_statement_end] = sym_statement_end,
  [sym_expression_begin] = sym_expression_begin,
  [sym_expression_end] = sym_expression_end,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LBRACE_POUND] = anon_sym_LBRACE_POUND,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_POUND_RBRACE] = anon_sym_POUND_RBRACE,
  [anon_sym_for] = anon_sym_for,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_endfor] = anon_sym_endfor,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_and] = anon_sym_and,
  [anon_sym_or] = anon_sym_or,
  [anon_sym_endif] = anon_sym_endif,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_elif] = anon_sym_elif,
  [anon_sym_raw] = anon_sym_raw,
  [anon_sym_endraw] = anon_sym_endraw,
  [anon_sym_macro] = anon_sym_macro,
  [anon_sym_endmacro] = anon_sym_endmacro,
  [anon_sym_extends] = anon_sym_extends,
  [anon_sym_block] = anon_sym_block,
  [anon_sym_endblock] = anon_sym_endblock,
  [anon_sym_call] = anon_sym_call,
  [anon_sym_endcall] = anon_sym_endcall,
  [anon_sym_filter] = anon_sym_filter,
  [anon_sym_endfilter] = anon_sym_endfilter,
  [anon_sym_set] = anon_sym_set,
  [anon_sym_endset] = anon_sym_endset,
  [anon_sym_include] = anon_sym_include,
  [anon_sym_import] = anon_sym_import,
  [anon_sym_from] = anon_sym_from,
  [anon_sym_autoescape] = anon_sym_autoescape,
  [anon_sym_endautoescape] = anon_sym_endautoescape,
  [anon_sym_trans] = anon_sym_trans,
  [anon_sym_endtrans] = anon_sym_endtrans,
  [anon_sym_pluralize] = anon_sym_pluralize,
  [anon_sym_with] = anon_sym_with,
  [anon_sym_endwith] = anon_sym_endwith,
  [anon_sym_debug] = anon_sym_debug,
  [anon_sym_do] = anon_sym_do,
  [anon_sym_is] = anon_sym_is,
  [sym__white_space] = sym__white_space,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_operator] = sym_operator,
  [sym_filter_operator] = sym_filter_operator,
  [sym_equal_operator] = sym_equal_operator,
  [sym_string] = sym_string,
  [sym_source_file] = sym_source_file,
  [sym__text] = sym__text,
  [sym__not] = sym__not,
  [sym__node] = sym__node,
  [sym_statement] = sym_statement,
  [sym_expression] = sym_expression,
  [sym_map] = sym_map,
  [sym__map_begin] = sym__map_begin,
  [sym__map_end] = sym__map_end,
  [sym_comment] = sym_comment,
  [sym_keyword] = sym_keyword,
  [aux_sym__inner_text] = aux_sym__inner_text,
  [aux_sym__inner_text2] = aux_sym__inner_text2,
  [sym_dotted_identifier] = sym_dotted_identifier,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_dotted_identifier_repeat1] = aux_sym_dotted_identifier_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__text_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__not_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__not_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__not_token3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__not_token4] = {
    .visible = false,
    .named = false,
  },
  [sym_statement_begin] = {
    .visible = true,
    .named = true,
  },
  [sym_statement_end] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_begin] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_end] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_POUND_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_for] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_endfor] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_and] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_or] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_endif] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_elif] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_raw] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_endraw] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_macro] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_endmacro] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_extends] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_block] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_endblock] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_call] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_endcall] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_filter] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_endfilter] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_set] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_endset] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_include] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_import] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_from] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_autoescape] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_endautoescape] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_trans] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_endtrans] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_pluralize] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_with] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_endwith] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_debug] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_do] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_is] = {
    .visible = true,
    .named = false,
  },
  [sym__white_space] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_filter_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_equal_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__text] = {
    .visible = false,
    .named = true,
  },
  [sym__not] = {
    .visible = false,
    .named = true,
  },
  [sym__node] = {
    .visible = false,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_map] = {
    .visible = true,
    .named = true,
  },
  [sym__map_begin] = {
    .visible = false,
    .named = true,
  },
  [sym__map_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__inner_text] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__inner_text2] = {
    .visible = false,
    .named = false,
  },
  [sym_dotted_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_dotted_identifier_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_attribute = 1,
  field_identifier = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_attribute] = "attribute",
  [field_identifier] = "identifier",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 1},
  [6] = {.index = 7, .length = 1},
  [7] = {.index = 8, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_identifier, 0},
  [1] =
    {field_attribute, 0},
    {field_attribute, 1, .inherited = true},
  [3] =
    {field_identifier, 1, .inherited = true},
  [4] =
    {field_identifier, 0, .inherited = true},
    {field_identifier, 1, .inherited = true},
  [6] =
    {field_identifier, 2, .inherited = true},
  [7] =
    {field_attribute, 1},
  [8] =
    {field_attribute, 0, .inherited = true},
    {field_attribute, 1, .inherited = true},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 17,
  [19] = 17,
  [20] = 16,
  [21] = 16,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 24,
  [26] = 26,
  [27] = 6,
  [28] = 7,
  [29] = 26,
  [30] = 6,
  [31] = 7,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 8,
  [38] = 8,
  [39] = 39,
  [40] = 12,
  [41] = 12,
  [42] = 39,
  [43] = 11,
  [44] = 11,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 48,
  [50] = 48,
};

static const TSCharacterRange sym_operator_character_set_1[] = {
  {0, 0x08}, {0x0e, 0x1f}, {'!', '!'}, {'$', '$'}, {'&', '&'}, {'(', '/'}, {':', '<'}, {'>', '@'},
  {'[', '^'}, {'`', '`'}, {'~', 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(16);
      ADVANCE_MAP(
        '#', 26,
        '%', 3,
        '.', 46,
        '=', 57,
        '{', 38,
        '|', 55,
        '}', 40,
        '"', 2,
        '\'', 2,
        '+', 50,
        '-', 50,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      if (lookahead != 0) ADVANCE(51);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '#', 26,
        '%', 3,
        '.', 46,
        '=', 57,
        '{', 38,
        '|', 55,
        '}', 40,
        '"', 2,
        '\'', 2,
        '+', 50,
        '-', 50,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      if (lookahead != 0) ADVANCE(51);
      END_STATE();
    case 2:
      if (lookahead == '#') ADVANCE(27);
      END_STATE();
    case 3:
      if (lookahead == '#') ADVANCE(27);
      if (lookahead == '}') ADVANCE(34);
      END_STATE();
    case 4:
      if (lookahead == '#') ADVANCE(12);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 5:
      ADVANCE_MAP(
        '%', 11,
        '.', 47,
        '=', 56,
        '{', 37,
        '|', 54,
        '"', 14,
        '\'', 14,
        '+', 52,
        '-', 52,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '#' &&
          (lookahead < 'a' || '}' < lookahead)) ADVANCE(53);
      END_STATE();
    case 6:
      ADVANCE_MAP(
        '%', 11,
        '=', 56,
        '{', 37,
        '|', 54,
        '"', 14,
        '\'', 14,
        '+', 52,
        '-', 52,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '#' &&
          (lookahead < 'a' || '}' < lookahead)) ADVANCE(53);
      END_STATE();
    case 7:
      if (lookahead == '.') ADVANCE(47);
      if (lookahead == '=') ADVANCE(56);
      if (lookahead == '{') ADVANCE(37);
      if (lookahead == '|') ADVANCE(54);
      if (lookahead == '}') ADVANCE(39);
      if (lookahead == '"' ||
          lookahead == '\'') ADVANCE(14);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '%') ADVANCE(53);
      END_STATE();
    case 8:
      if (lookahead == '.') ADVANCE(47);
      if (lookahead == '=') ADVANCE(56);
      if (lookahead == '{') ADVANCE(37);
      if (lookahead == '|') ADVANCE(54);
      if (lookahead == '}') ADVANCE(13);
      if (lookahead == '"' ||
          lookahead == '\'') ADVANCE(14);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '%') ADVANCE(53);
      END_STATE();
    case 9:
      if (lookahead == '=') ADVANCE(56);
      if (lookahead == '{') ADVANCE(37);
      if (lookahead == '|') ADVANCE(54);
      if (lookahead == '}') ADVANCE(39);
      if (lookahead == '"' ||
          lookahead == '\'') ADVANCE(14);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '%') ADVANCE(53);
      END_STATE();
    case 10:
      if (lookahead == '=') ADVANCE(56);
      if (lookahead == '{') ADVANCE(37);
      if (lookahead == '|') ADVANCE(54);
      if (lookahead == '}') ADVANCE(13);
      if (lookahead == '"' ||
          lookahead == '\'') ADVANCE(14);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '%') ADVANCE(53);
      END_STATE();
    case 11:
      if (lookahead == '}') ADVANCE(34);
      END_STATE();
    case 12:
      if (lookahead == '}') ADVANCE(44);
      END_STATE();
    case 13:
      if (lookahead == '}') ADVANCE(36);
      END_STATE();
    case 14:
      if (lookahead == '"' ||
          lookahead == '\'') ADVANCE(58);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 15:
      if (eof) ADVANCE(16);
      if (lookahead == '#') ADVANCE(25);
      if (lookahead == '%') ADVANCE(30);
      if (lookahead == '{') ADVANCE(21);
      if (lookahead == '}') ADVANCE(23);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(18);
      if (lookahead != 0) ADVANCE(17);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym__text_token1);
      if (lookahead == '#') ADVANCE(27);
      if (lookahead == '%') ADVANCE(31);
      if (lookahead == '}') ADVANCE(22);
      if (lookahead != 0 &&
          lookahead != '{') ADVANCE(19);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym__text_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '#' &&
          lookahead != '%' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(17);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym__text_token1);
      if (lookahead != 0 &&
          lookahead != '#' &&
          lookahead != '%' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym__not_token1);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym__not_token1);
      if (lookahead == '#') ADVANCE(41);
      if (lookahead == '%') ADVANCE(33);
      if (lookahead == '{') ADVANCE(35);
      if (lookahead == '}') ADVANCE(20);
      if (lookahead != 0) ADVANCE(20);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym__not_token2);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym__not_token2);
      if (lookahead == '#') ADVANCE(27);
      if (lookahead == '%') ADVANCE(31);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym__not_token3);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym__not_token3);
      if (lookahead == '#') ADVANCE(27);
      if (lookahead == '%') ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(24);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym__not_token3);
      if (lookahead == '#') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(24);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym__not_token3);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(24);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym__not_token3);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(29);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym__not_token4);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym__not_token4);
      if (lookahead == '#') ADVANCE(27);
      if (lookahead == '%') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(29);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym__not_token4);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(29);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_statement_begin);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_statement_begin);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(32);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_statement_end);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_expression_begin);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_expression_end);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead == '#') ADVANCE(41);
      if (lookahead == '%') ADVANCE(33);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      if (lookahead == '#') ADVANCE(27);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_LBRACE_POUND);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != '#') ADVANCE(43);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '#') ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_POUND_RBRACE);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym__white_space);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_DOT);
      if (lookahead == '#') ADVANCE(27);
      if ((!eof && set_contains(sym_operator_character_set_1, 11, lookahead))) ADVANCE(53);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_DOT);
      if ((!eof && set_contains(sym_operator_character_set_1, 11, lookahead))) ADVANCE(53);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '#') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_operator);
      if (lookahead == '#') ADVANCE(27);
      if (lookahead == '%') ADVANCE(11);
      if ((!eof && set_contains(sym_operator_character_set_1, 11, lookahead))) ADVANCE(53);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_operator);
      if (lookahead == '#') ADVANCE(27);
      if ((!eof && set_contains(sym_operator_character_set_1, 11, lookahead))) ADVANCE(53);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_operator);
      if (lookahead == '%') ADVANCE(11);
      if ((!eof && set_contains(sym_operator_character_set_1, 11, lookahead))) ADVANCE(53);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_operator);
      if ((!eof && set_contains(sym_operator_character_set_1, 11, lookahead))) ADVANCE(53);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_filter_operator);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_filter_operator);
      if (lookahead == '#') ADVANCE(27);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_equal_operator);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_equal_operator);
      if (lookahead == '#') ADVANCE(27);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'a', 1,
        'b', 2,
        'c', 3,
        'd', 4,
        'e', 5,
        'f', 6,
        'i', 7,
        'm', 8,
        'o', 9,
        'p', 10,
        'r', 11,
        's', 12,
        't', 13,
        'w', 14,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'n') ADVANCE(15);
      if (lookahead == 'u') ADVANCE(16);
      END_STATE();
    case 2:
      if (lookahead == 'l') ADVANCE(17);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(18);
      END_STATE();
    case 4:
      if (lookahead == 'e') ADVANCE(19);
      if (lookahead == 'o') ADVANCE(20);
      END_STATE();
    case 5:
      if (lookahead == 'l') ADVANCE(21);
      if (lookahead == 'n') ADVANCE(22);
      if (lookahead == 'x') ADVANCE(23);
      END_STATE();
    case 6:
      if (lookahead == 'i') ADVANCE(24);
      if (lookahead == 'o') ADVANCE(25);
      if (lookahead == 'r') ADVANCE(26);
      END_STATE();
    case 7:
      if (lookahead == 'f') ADVANCE(27);
      if (lookahead == 'm') ADVANCE(28);
      if (lookahead == 'n') ADVANCE(29);
      if (lookahead == 's') ADVANCE(30);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(31);
      END_STATE();
    case 9:
      if (lookahead == 'r') ADVANCE(32);
      END_STATE();
    case 10:
      if (lookahead == 'l') ADVANCE(33);
      END_STATE();
    case 11:
      if (lookahead == 'a') ADVANCE(34);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(35);
      END_STATE();
    case 13:
      if (lookahead == 'r') ADVANCE(36);
      END_STATE();
    case 14:
      if (lookahead == 'i') ADVANCE(37);
      END_STATE();
    case 15:
      if (lookahead == 'd') ADVANCE(38);
      END_STATE();
    case 16:
      if (lookahead == 't') ADVANCE(39);
      END_STATE();
    case 17:
      if (lookahead == 'o') ADVANCE(40);
      END_STATE();
    case 18:
      if (lookahead == 'l') ADVANCE(41);
      END_STATE();
    case 19:
      if (lookahead == 'b') ADVANCE(42);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_do);
      END_STATE();
    case 21:
      if (lookahead == 'i') ADVANCE(43);
      if (lookahead == 's') ADVANCE(44);
      END_STATE();
    case 22:
      if (lookahead == 'd') ADVANCE(45);
      END_STATE();
    case 23:
      if (lookahead == 't') ADVANCE(46);
      END_STATE();
    case 24:
      if (lookahead == 'l') ADVANCE(47);
      END_STATE();
    case 25:
      if (lookahead == 'r') ADVANCE(48);
      END_STATE();
    case 26:
      if (lookahead == 'o') ADVANCE(49);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 28:
      if (lookahead == 'p') ADVANCE(50);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_in);
      if (lookahead == 'c') ADVANCE(51);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_is);
      END_STATE();
    case 31:
      if (lookahead == 'c') ADVANCE(52);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_or);
      END_STATE();
    case 33:
      if (lookahead == 'u') ADVANCE(53);
      END_STATE();
    case 34:
      if (lookahead == 'w') ADVANCE(54);
      END_STATE();
    case 35:
      if (lookahead == 't') ADVANCE(55);
      END_STATE();
    case 36:
      if (lookahead == 'a') ADVANCE(56);
      END_STATE();
    case 37:
      if (lookahead == 't') ADVANCE(57);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_and);
      END_STATE();
    case 39:
      if (lookahead == 'o') ADVANCE(58);
      END_STATE();
    case 40:
      if (lookahead == 'c') ADVANCE(59);
      END_STATE();
    case 41:
      if (lookahead == 'l') ADVANCE(60);
      END_STATE();
    case 42:
      if (lookahead == 'u') ADVANCE(61);
      END_STATE();
    case 43:
      if (lookahead == 'f') ADVANCE(62);
      END_STATE();
    case 44:
      if (lookahead == 'e') ADVANCE(63);
      END_STATE();
    case 45:
      ADVANCE_MAP(
        'a', 64,
        'b', 65,
        'c', 66,
        'f', 67,
        'i', 68,
        'm', 69,
        'r', 70,
        's', 71,
        't', 72,
        'w', 73,
      );
      END_STATE();
    case 46:
      if (lookahead == 'e') ADVANCE(74);
      END_STATE();
    case 47:
      if (lookahead == 't') ADVANCE(75);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_for);
      END_STATE();
    case 49:
      if (lookahead == 'm') ADVANCE(76);
      END_STATE();
    case 50:
      if (lookahead == 'o') ADVANCE(77);
      END_STATE();
    case 51:
      if (lookahead == 'l') ADVANCE(78);
      END_STATE();
    case 52:
      if (lookahead == 'r') ADVANCE(79);
      END_STATE();
    case 53:
      if (lookahead == 'r') ADVANCE(80);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_raw);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_set);
      END_STATE();
    case 56:
      if (lookahead == 'n') ADVANCE(81);
      END_STATE();
    case 57:
      if (lookahead == 'h') ADVANCE(82);
      END_STATE();
    case 58:
      if (lookahead == 'e') ADVANCE(83);
      END_STATE();
    case 59:
      if (lookahead == 'k') ADVANCE(84);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_call);
      END_STATE();
    case 61:
      if (lookahead == 'g') ADVANCE(85);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_elif);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 64:
      if (lookahead == 'u') ADVANCE(86);
      END_STATE();
    case 65:
      if (lookahead == 'l') ADVANCE(87);
      END_STATE();
    case 66:
      if (lookahead == 'a') ADVANCE(88);
      END_STATE();
    case 67:
      if (lookahead == 'i') ADVANCE(89);
      if (lookahead == 'o') ADVANCE(90);
      END_STATE();
    case 68:
      if (lookahead == 'f') ADVANCE(91);
      END_STATE();
    case 69:
      if (lookahead == 'a') ADVANCE(92);
      END_STATE();
    case 70:
      if (lookahead == 'a') ADVANCE(93);
      END_STATE();
    case 71:
      if (lookahead == 'e') ADVANCE(94);
      END_STATE();
    case 72:
      if (lookahead == 'r') ADVANCE(95);
      END_STATE();
    case 73:
      if (lookahead == 'i') ADVANCE(96);
      END_STATE();
    case 74:
      if (lookahead == 'n') ADVANCE(97);
      END_STATE();
    case 75:
      if (lookahead == 'e') ADVANCE(98);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_from);
      END_STATE();
    case 77:
      if (lookahead == 'r') ADVANCE(99);
      END_STATE();
    case 78:
      if (lookahead == 'u') ADVANCE(100);
      END_STATE();
    case 79:
      if (lookahead == 'o') ADVANCE(101);
      END_STATE();
    case 80:
      if (lookahead == 'a') ADVANCE(102);
      END_STATE();
    case 81:
      if (lookahead == 's') ADVANCE(103);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_with);
      END_STATE();
    case 83:
      if (lookahead == 's') ADVANCE(104);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_block);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_debug);
      END_STATE();
    case 86:
      if (lookahead == 't') ADVANCE(105);
      END_STATE();
    case 87:
      if (lookahead == 'o') ADVANCE(106);
      END_STATE();
    case 88:
      if (lookahead == 'l') ADVANCE(107);
      END_STATE();
    case 89:
      if (lookahead == 'l') ADVANCE(108);
      END_STATE();
    case 90:
      if (lookahead == 'r') ADVANCE(109);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_endif);
      END_STATE();
    case 92:
      if (lookahead == 'c') ADVANCE(110);
      END_STATE();
    case 93:
      if (lookahead == 'w') ADVANCE(111);
      END_STATE();
    case 94:
      if (lookahead == 't') ADVANCE(112);
      END_STATE();
    case 95:
      if (lookahead == 'a') ADVANCE(113);
      END_STATE();
    case 96:
      if (lookahead == 't') ADVANCE(114);
      END_STATE();
    case 97:
      if (lookahead == 'd') ADVANCE(115);
      END_STATE();
    case 98:
      if (lookahead == 'r') ADVANCE(116);
      END_STATE();
    case 99:
      if (lookahead == 't') ADVANCE(117);
      END_STATE();
    case 100:
      if (lookahead == 'd') ADVANCE(118);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_macro);
      END_STATE();
    case 102:
      if (lookahead == 'l') ADVANCE(119);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(anon_sym_trans);
      END_STATE();
    case 104:
      if (lookahead == 'c') ADVANCE(120);
      END_STATE();
    case 105:
      if (lookahead == 'o') ADVANCE(121);
      END_STATE();
    case 106:
      if (lookahead == 'c') ADVANCE(122);
      END_STATE();
    case 107:
      if (lookahead == 'l') ADVANCE(123);
      END_STATE();
    case 108:
      if (lookahead == 't') ADVANCE(124);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(anon_sym_endfor);
      END_STATE();
    case 110:
      if (lookahead == 'r') ADVANCE(125);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(anon_sym_endraw);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(anon_sym_endset);
      END_STATE();
    case 113:
      if (lookahead == 'n') ADVANCE(126);
      END_STATE();
    case 114:
      if (lookahead == 'h') ADVANCE(127);
      END_STATE();
    case 115:
      if (lookahead == 's') ADVANCE(128);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(anon_sym_filter);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(anon_sym_import);
      END_STATE();
    case 118:
      if (lookahead == 'e') ADVANCE(129);
      END_STATE();
    case 119:
      if (lookahead == 'i') ADVANCE(130);
      END_STATE();
    case 120:
      if (lookahead == 'a') ADVANCE(131);
      END_STATE();
    case 121:
      if (lookahead == 'e') ADVANCE(132);
      END_STATE();
    case 122:
      if (lookahead == 'k') ADVANCE(133);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(anon_sym_endcall);
      END_STATE();
    case 124:
      if (lookahead == 'e') ADVANCE(134);
      END_STATE();
    case 125:
      if (lookahead == 'o') ADVANCE(135);
      END_STATE();
    case 126:
      if (lookahead == 's') ADVANCE(136);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(anon_sym_endwith);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(anon_sym_extends);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(anon_sym_include);
      END_STATE();
    case 130:
      if (lookahead == 'z') ADVANCE(137);
      END_STATE();
    case 131:
      if (lookahead == 'p') ADVANCE(138);
      END_STATE();
    case 132:
      if (lookahead == 's') ADVANCE(139);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(anon_sym_endblock);
      END_STATE();
    case 134:
      if (lookahead == 'r') ADVANCE(140);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(anon_sym_endmacro);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(anon_sym_endtrans);
      END_STATE();
    case 137:
      if (lookahead == 'e') ADVANCE(141);
      END_STATE();
    case 138:
      if (lookahead == 'e') ADVANCE(142);
      END_STATE();
    case 139:
      if (lookahead == 'c') ADVANCE(143);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(anon_sym_endfilter);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(anon_sym_pluralize);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(anon_sym_autoescape);
      END_STATE();
    case 143:
      if (lookahead == 'a') ADVANCE(144);
      END_STATE();
    case 144:
      if (lookahead == 'p') ADVANCE(145);
      END_STATE();
    case 145:
      if (lookahead == 'e') ADVANCE(146);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(anon_sym_endautoescape);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 15},
  [2] = {.lex_state = 6},
  [3] = {.lex_state = 6},
  [4] = {.lex_state = 6},
  [5] = {.lex_state = 5},
  [6] = {.lex_state = 5},
  [7] = {.lex_state = 5},
  [8] = {.lex_state = 5},
  [9] = {.lex_state = 6},
  [10] = {.lex_state = 6},
  [11] = {.lex_state = 6},
  [12] = {.lex_state = 6},
  [13] = {.lex_state = 4},
  [14] = {.lex_state = 15},
  [15] = {.lex_state = 15},
  [16] = {.lex_state = 9},
  [17] = {.lex_state = 9},
  [18] = {.lex_state = 9},
  [19] = {.lex_state = 9},
  [20] = {.lex_state = 9},
  [21] = {.lex_state = 9},
  [22] = {.lex_state = 10},
  [23] = {.lex_state = 10},
  [24] = {.lex_state = 10},
  [25] = {.lex_state = 9},
  [26] = {.lex_state = 8},
  [27] = {.lex_state = 8},
  [28] = {.lex_state = 8},
  [29] = {.lex_state = 7},
  [30] = {.lex_state = 7},
  [31] = {.lex_state = 7},
  [32] = {.lex_state = 15},
  [33] = {.lex_state = 15},
  [34] = {.lex_state = 15},
  [35] = {.lex_state = 15},
  [36] = {.lex_state = 15},
  [37] = {.lex_state = 7},
  [38] = {.lex_state = 8},
  [39] = {.lex_state = 9},
  [40] = {.lex_state = 10},
  [41] = {.lex_state = 9},
  [42] = {.lex_state = 10},
  [43] = {.lex_state = 9},
  [44] = {.lex_state = 10},
  [45] = {.lex_state = 42},
  [46] = {.lex_state = 4},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 4},
  [49] = {.lex_state = 4},
  [50] = {.lex_state = 4},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [aux_sym__not_token3] = ACTIONS(1),
    [sym_statement_begin] = ACTIONS(1),
    [sym_statement_end] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACE_POUND] = ACTIONS(1),
    [anon_sym_for] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_endfor] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_and] = ACTIONS(1),
    [anon_sym_or] = ACTIONS(1),
    [anon_sym_endif] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_elif] = ACTIONS(1),
    [anon_sym_raw] = ACTIONS(1),
    [anon_sym_endraw] = ACTIONS(1),
    [anon_sym_macro] = ACTIONS(1),
    [anon_sym_endmacro] = ACTIONS(1),
    [anon_sym_extends] = ACTIONS(1),
    [anon_sym_block] = ACTIONS(1),
    [anon_sym_endblock] = ACTIONS(1),
    [anon_sym_call] = ACTIONS(1),
    [anon_sym_endcall] = ACTIONS(1),
    [anon_sym_filter] = ACTIONS(1),
    [anon_sym_endfilter] = ACTIONS(1),
    [anon_sym_set] = ACTIONS(1),
    [anon_sym_endset] = ACTIONS(1),
    [anon_sym_include] = ACTIONS(1),
    [anon_sym_import] = ACTIONS(1),
    [anon_sym_from] = ACTIONS(1),
    [anon_sym_autoescape] = ACTIONS(1),
    [anon_sym_endautoescape] = ACTIONS(1),
    [anon_sym_trans] = ACTIONS(1),
    [anon_sym_endtrans] = ACTIONS(1),
    [anon_sym_pluralize] = ACTIONS(1),
    [anon_sym_with] = ACTIONS(1),
    [anon_sym_endwith] = ACTIONS(1),
    [anon_sym_debug] = ACTIONS(1),
    [anon_sym_do] = ACTIONS(1),
    [anon_sym_is] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym_operator] = ACTIONS(1),
    [sym_filter_operator] = ACTIONS(1),
    [sym_equal_operator] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(47),
    [sym__text] = STATE(15),
    [sym__not] = STATE(15),
    [sym__node] = STATE(15),
    [sym_statement] = STATE(15),
    [sym_expression] = STATE(15),
    [sym_comment] = STATE(15),
    [aux_sym_source_file_repeat1] = STATE(15),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym__text_token1] = ACTIONS(5),
    [aux_sym__not_token1] = ACTIONS(5),
    [aux_sym__not_token2] = ACTIONS(5),
    [aux_sym__not_token3] = ACTIONS(5),
    [aux_sym__not_token4] = ACTIONS(5),
    [sym_statement_begin] = ACTIONS(7),
    [sym_expression_begin] = ACTIONS(9),
    [anon_sym_LBRACE_POUND] = ACTIONS(11),
  },
  [STATE(2)] = {
    [sym_map] = STATE(3),
    [sym__map_begin] = STATE(20),
    [sym_keyword] = STATE(3),
    [aux_sym__inner_text] = STATE(3),
    [sym_dotted_identifier] = STATE(10),
    [sym_identifier] = ACTIONS(13),
    [sym_statement_end] = ACTIONS(15),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_for] = ACTIONS(19),
    [anon_sym_in] = ACTIONS(19),
    [anon_sym_endfor] = ACTIONS(19),
    [anon_sym_if] = ACTIONS(19),
    [anon_sym_and] = ACTIONS(19),
    [anon_sym_or] = ACTIONS(19),
    [anon_sym_endif] = ACTIONS(19),
    [anon_sym_else] = ACTIONS(19),
    [anon_sym_elif] = ACTIONS(19),
    [anon_sym_raw] = ACTIONS(19),
    [anon_sym_endraw] = ACTIONS(19),
    [anon_sym_macro] = ACTIONS(19),
    [anon_sym_endmacro] = ACTIONS(19),
    [anon_sym_extends] = ACTIONS(19),
    [anon_sym_block] = ACTIONS(19),
    [anon_sym_endblock] = ACTIONS(19),
    [anon_sym_call] = ACTIONS(19),
    [anon_sym_endcall] = ACTIONS(19),
    [anon_sym_filter] = ACTIONS(19),
    [anon_sym_endfilter] = ACTIONS(19),
    [anon_sym_set] = ACTIONS(19),
    [anon_sym_endset] = ACTIONS(19),
    [anon_sym_include] = ACTIONS(19),
    [anon_sym_import] = ACTIONS(19),
    [anon_sym_from] = ACTIONS(19),
    [anon_sym_autoescape] = ACTIONS(19),
    [anon_sym_endautoescape] = ACTIONS(19),
    [anon_sym_trans] = ACTIONS(19),
    [anon_sym_endtrans] = ACTIONS(19),
    [anon_sym_pluralize] = ACTIONS(19),
    [anon_sym_with] = ACTIONS(19),
    [anon_sym_endwith] = ACTIONS(19),
    [anon_sym_debug] = ACTIONS(19),
    [anon_sym_do] = ACTIONS(19),
    [anon_sym_is] = ACTIONS(19),
    [sym__white_space] = ACTIONS(21),
    [sym_operator] = ACTIONS(23),
    [sym_filter_operator] = ACTIONS(23),
    [sym_equal_operator] = ACTIONS(23),
    [sym_string] = ACTIONS(23),
  },
  [STATE(3)] = {
    [sym_map] = STATE(4),
    [sym__map_begin] = STATE(20),
    [sym_keyword] = STATE(4),
    [aux_sym__inner_text] = STATE(4),
    [sym_dotted_identifier] = STATE(10),
    [sym_identifier] = ACTIONS(13),
    [sym_statement_end] = ACTIONS(25),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_for] = ACTIONS(19),
    [anon_sym_in] = ACTIONS(19),
    [anon_sym_endfor] = ACTIONS(19),
    [anon_sym_if] = ACTIONS(19),
    [anon_sym_and] = ACTIONS(19),
    [anon_sym_or] = ACTIONS(19),
    [anon_sym_endif] = ACTIONS(19),
    [anon_sym_else] = ACTIONS(19),
    [anon_sym_elif] = ACTIONS(19),
    [anon_sym_raw] = ACTIONS(19),
    [anon_sym_endraw] = ACTIONS(19),
    [anon_sym_macro] = ACTIONS(19),
    [anon_sym_endmacro] = ACTIONS(19),
    [anon_sym_extends] = ACTIONS(19),
    [anon_sym_block] = ACTIONS(19),
    [anon_sym_endblock] = ACTIONS(19),
    [anon_sym_call] = ACTIONS(19),
    [anon_sym_endcall] = ACTIONS(19),
    [anon_sym_filter] = ACTIONS(19),
    [anon_sym_endfilter] = ACTIONS(19),
    [anon_sym_set] = ACTIONS(19),
    [anon_sym_endset] = ACTIONS(19),
    [anon_sym_include] = ACTIONS(19),
    [anon_sym_import] = ACTIONS(19),
    [anon_sym_from] = ACTIONS(19),
    [anon_sym_autoescape] = ACTIONS(19),
    [anon_sym_endautoescape] = ACTIONS(19),
    [anon_sym_trans] = ACTIONS(19),
    [anon_sym_endtrans] = ACTIONS(19),
    [anon_sym_pluralize] = ACTIONS(19),
    [anon_sym_with] = ACTIONS(19),
    [anon_sym_endwith] = ACTIONS(19),
    [anon_sym_debug] = ACTIONS(19),
    [anon_sym_do] = ACTIONS(19),
    [anon_sym_is] = ACTIONS(19),
    [sym__white_space] = ACTIONS(27),
    [sym_operator] = ACTIONS(29),
    [sym_filter_operator] = ACTIONS(29),
    [sym_equal_operator] = ACTIONS(29),
    [sym_string] = ACTIONS(29),
  },
  [STATE(4)] = {
    [sym_map] = STATE(4),
    [sym__map_begin] = STATE(20),
    [sym_keyword] = STATE(4),
    [aux_sym__inner_text] = STATE(4),
    [sym_dotted_identifier] = STATE(10),
    [sym_identifier] = ACTIONS(31),
    [sym_statement_end] = ACTIONS(34),
    [anon_sym_LBRACE] = ACTIONS(36),
    [anon_sym_for] = ACTIONS(39),
    [anon_sym_in] = ACTIONS(39),
    [anon_sym_endfor] = ACTIONS(39),
    [anon_sym_if] = ACTIONS(39),
    [anon_sym_and] = ACTIONS(39),
    [anon_sym_or] = ACTIONS(39),
    [anon_sym_endif] = ACTIONS(39),
    [anon_sym_else] = ACTIONS(39),
    [anon_sym_elif] = ACTIONS(39),
    [anon_sym_raw] = ACTIONS(39),
    [anon_sym_endraw] = ACTIONS(39),
    [anon_sym_macro] = ACTIONS(39),
    [anon_sym_endmacro] = ACTIONS(39),
    [anon_sym_extends] = ACTIONS(39),
    [anon_sym_block] = ACTIONS(39),
    [anon_sym_endblock] = ACTIONS(39),
    [anon_sym_call] = ACTIONS(39),
    [anon_sym_endcall] = ACTIONS(39),
    [anon_sym_filter] = ACTIONS(39),
    [anon_sym_endfilter] = ACTIONS(39),
    [anon_sym_set] = ACTIONS(39),
    [anon_sym_endset] = ACTIONS(39),
    [anon_sym_include] = ACTIONS(39),
    [anon_sym_import] = ACTIONS(39),
    [anon_sym_from] = ACTIONS(39),
    [anon_sym_autoescape] = ACTIONS(39),
    [anon_sym_endautoescape] = ACTIONS(39),
    [anon_sym_trans] = ACTIONS(39),
    [anon_sym_endtrans] = ACTIONS(39),
    [anon_sym_pluralize] = ACTIONS(39),
    [anon_sym_with] = ACTIONS(39),
    [anon_sym_endwith] = ACTIONS(39),
    [anon_sym_debug] = ACTIONS(39),
    [anon_sym_do] = ACTIONS(39),
    [anon_sym_is] = ACTIONS(39),
    [sym__white_space] = ACTIONS(42),
    [sym_operator] = ACTIONS(45),
    [sym_filter_operator] = ACTIONS(45),
    [sym_equal_operator] = ACTIONS(45),
    [sym_string] = ACTIONS(45),
  },
  [STATE(5)] = {
    [aux_sym_dotted_identifier_repeat1] = STATE(6),
    [sym_identifier] = ACTIONS(48),
    [sym_statement_end] = ACTIONS(48),
    [anon_sym_LBRACE] = ACTIONS(48),
    [anon_sym_for] = ACTIONS(48),
    [anon_sym_in] = ACTIONS(48),
    [anon_sym_endfor] = ACTIONS(48),
    [anon_sym_if] = ACTIONS(48),
    [anon_sym_and] = ACTIONS(48),
    [anon_sym_or] = ACTIONS(48),
    [anon_sym_endif] = ACTIONS(48),
    [anon_sym_else] = ACTIONS(48),
    [anon_sym_elif] = ACTIONS(48),
    [anon_sym_raw] = ACTIONS(48),
    [anon_sym_endraw] = ACTIONS(48),
    [anon_sym_macro] = ACTIONS(48),
    [anon_sym_endmacro] = ACTIONS(48),
    [anon_sym_extends] = ACTIONS(48),
    [anon_sym_block] = ACTIONS(48),
    [anon_sym_endblock] = ACTIONS(48),
    [anon_sym_call] = ACTIONS(48),
    [anon_sym_endcall] = ACTIONS(48),
    [anon_sym_filter] = ACTIONS(48),
    [anon_sym_endfilter] = ACTIONS(48),
    [anon_sym_set] = ACTIONS(48),
    [anon_sym_endset] = ACTIONS(48),
    [anon_sym_include] = ACTIONS(48),
    [anon_sym_import] = ACTIONS(48),
    [anon_sym_from] = ACTIONS(48),
    [anon_sym_autoescape] = ACTIONS(48),
    [anon_sym_endautoescape] = ACTIONS(48),
    [anon_sym_trans] = ACTIONS(48),
    [anon_sym_endtrans] = ACTIONS(48),
    [anon_sym_pluralize] = ACTIONS(48),
    [anon_sym_with] = ACTIONS(48),
    [anon_sym_endwith] = ACTIONS(48),
    [anon_sym_debug] = ACTIONS(48),
    [anon_sym_do] = ACTIONS(48),
    [anon_sym_is] = ACTIONS(48),
    [sym__white_space] = ACTIONS(50),
    [anon_sym_DOT] = ACTIONS(52),
    [sym_operator] = ACTIONS(48),
    [sym_filter_operator] = ACTIONS(48),
    [sym_equal_operator] = ACTIONS(48),
    [sym_string] = ACTIONS(48),
  },
  [STATE(6)] = {
    [aux_sym_dotted_identifier_repeat1] = STATE(7),
    [sym_identifier] = ACTIONS(54),
    [sym_statement_end] = ACTIONS(54),
    [anon_sym_LBRACE] = ACTIONS(54),
    [anon_sym_for] = ACTIONS(54),
    [anon_sym_in] = ACTIONS(54),
    [anon_sym_endfor] = ACTIONS(54),
    [anon_sym_if] = ACTIONS(54),
    [anon_sym_and] = ACTIONS(54),
    [anon_sym_or] = ACTIONS(54),
    [anon_sym_endif] = ACTIONS(54),
    [anon_sym_else] = ACTIONS(54),
    [anon_sym_elif] = ACTIONS(54),
    [anon_sym_raw] = ACTIONS(54),
    [anon_sym_endraw] = ACTIONS(54),
    [anon_sym_macro] = ACTIONS(54),
    [anon_sym_endmacro] = ACTIONS(54),
    [anon_sym_extends] = ACTIONS(54),
    [anon_sym_block] = ACTIONS(54),
    [anon_sym_endblock] = ACTIONS(54),
    [anon_sym_call] = ACTIONS(54),
    [anon_sym_endcall] = ACTIONS(54),
    [anon_sym_filter] = ACTIONS(54),
    [anon_sym_endfilter] = ACTIONS(54),
    [anon_sym_set] = ACTIONS(54),
    [anon_sym_endset] = ACTIONS(54),
    [anon_sym_include] = ACTIONS(54),
    [anon_sym_import] = ACTIONS(54),
    [anon_sym_from] = ACTIONS(54),
    [anon_sym_autoescape] = ACTIONS(54),
    [anon_sym_endautoescape] = ACTIONS(54),
    [anon_sym_trans] = ACTIONS(54),
    [anon_sym_endtrans] = ACTIONS(54),
    [anon_sym_pluralize] = ACTIONS(54),
    [anon_sym_with] = ACTIONS(54),
    [anon_sym_endwith] = ACTIONS(54),
    [anon_sym_debug] = ACTIONS(54),
    [anon_sym_do] = ACTIONS(54),
    [anon_sym_is] = ACTIONS(54),
    [sym__white_space] = ACTIONS(56),
    [anon_sym_DOT] = ACTIONS(52),
    [sym_operator] = ACTIONS(54),
    [sym_filter_operator] = ACTIONS(54),
    [sym_equal_operator] = ACTIONS(54),
    [sym_string] = ACTIONS(54),
  },
  [STATE(7)] = {
    [aux_sym_dotted_identifier_repeat1] = STATE(7),
    [sym_identifier] = ACTIONS(58),
    [sym_statement_end] = ACTIONS(58),
    [anon_sym_LBRACE] = ACTIONS(58),
    [anon_sym_for] = ACTIONS(58),
    [anon_sym_in] = ACTIONS(58),
    [anon_sym_endfor] = ACTIONS(58),
    [anon_sym_if] = ACTIONS(58),
    [anon_sym_and] = ACTIONS(58),
    [anon_sym_or] = ACTIONS(58),
    [anon_sym_endif] = ACTIONS(58),
    [anon_sym_else] = ACTIONS(58),
    [anon_sym_elif] = ACTIONS(58),
    [anon_sym_raw] = ACTIONS(58),
    [anon_sym_endraw] = ACTIONS(58),
    [anon_sym_macro] = ACTIONS(58),
    [anon_sym_endmacro] = ACTIONS(58),
    [anon_sym_extends] = ACTIONS(58),
    [anon_sym_block] = ACTIONS(58),
    [anon_sym_endblock] = ACTIONS(58),
    [anon_sym_call] = ACTIONS(58),
    [anon_sym_endcall] = ACTIONS(58),
    [anon_sym_filter] = ACTIONS(58),
    [anon_sym_endfilter] = ACTIONS(58),
    [anon_sym_set] = ACTIONS(58),
    [anon_sym_endset] = ACTIONS(58),
    [anon_sym_include] = ACTIONS(58),
    [anon_sym_import] = ACTIONS(58),
    [anon_sym_from] = ACTIONS(58),
    [anon_sym_autoescape] = ACTIONS(58),
    [anon_sym_endautoescape] = ACTIONS(58),
    [anon_sym_trans] = ACTIONS(58),
    [anon_sym_endtrans] = ACTIONS(58),
    [anon_sym_pluralize] = ACTIONS(58),
    [anon_sym_with] = ACTIONS(58),
    [anon_sym_endwith] = ACTIONS(58),
    [anon_sym_debug] = ACTIONS(58),
    [anon_sym_do] = ACTIONS(58),
    [anon_sym_is] = ACTIONS(58),
    [sym__white_space] = ACTIONS(60),
    [anon_sym_DOT] = ACTIONS(62),
    [sym_operator] = ACTIONS(58),
    [sym_filter_operator] = ACTIONS(58),
    [sym_equal_operator] = ACTIONS(58),
    [sym_string] = ACTIONS(58),
  },
  [STATE(8)] = {
    [sym_identifier] = ACTIONS(65),
    [sym_statement_end] = ACTIONS(65),
    [anon_sym_LBRACE] = ACTIONS(65),
    [anon_sym_for] = ACTIONS(65),
    [anon_sym_in] = ACTIONS(65),
    [anon_sym_endfor] = ACTIONS(65),
    [anon_sym_if] = ACTIONS(65),
    [anon_sym_and] = ACTIONS(65),
    [anon_sym_or] = ACTIONS(65),
    [anon_sym_endif] = ACTIONS(65),
    [anon_sym_else] = ACTIONS(65),
    [anon_sym_elif] = ACTIONS(65),
    [anon_sym_raw] = ACTIONS(65),
    [anon_sym_endraw] = ACTIONS(65),
    [anon_sym_macro] = ACTIONS(65),
    [anon_sym_endmacro] = ACTIONS(65),
    [anon_sym_extends] = ACTIONS(65),
    [anon_sym_block] = ACTIONS(65),
    [anon_sym_endblock] = ACTIONS(65),
    [anon_sym_call] = ACTIONS(65),
    [anon_sym_endcall] = ACTIONS(65),
    [anon_sym_filter] = ACTIONS(65),
    [anon_sym_endfilter] = ACTIONS(65),
    [anon_sym_set] = ACTIONS(65),
    [anon_sym_endset] = ACTIONS(65),
    [anon_sym_include] = ACTIONS(65),
    [anon_sym_import] = ACTIONS(65),
    [anon_sym_from] = ACTIONS(65),
    [anon_sym_autoescape] = ACTIONS(65),
    [anon_sym_endautoescape] = ACTIONS(65),
    [anon_sym_trans] = ACTIONS(65),
    [anon_sym_endtrans] = ACTIONS(65),
    [anon_sym_pluralize] = ACTIONS(65),
    [anon_sym_with] = ACTIONS(65),
    [anon_sym_endwith] = ACTIONS(65),
    [anon_sym_debug] = ACTIONS(65),
    [anon_sym_do] = ACTIONS(65),
    [anon_sym_is] = ACTIONS(65),
    [sym__white_space] = ACTIONS(67),
    [anon_sym_DOT] = ACTIONS(65),
    [sym_operator] = ACTIONS(65),
    [sym_filter_operator] = ACTIONS(65),
    [sym_equal_operator] = ACTIONS(65),
    [sym_string] = ACTIONS(65),
  },
  [STATE(9)] = {
    [sym_identifier] = ACTIONS(69),
    [sym_statement_end] = ACTIONS(69),
    [anon_sym_LBRACE] = ACTIONS(69),
    [anon_sym_for] = ACTIONS(69),
    [anon_sym_in] = ACTIONS(69),
    [anon_sym_endfor] = ACTIONS(69),
    [anon_sym_if] = ACTIONS(69),
    [anon_sym_and] = ACTIONS(69),
    [anon_sym_or] = ACTIONS(69),
    [anon_sym_endif] = ACTIONS(69),
    [anon_sym_else] = ACTIONS(69),
    [anon_sym_elif] = ACTIONS(69),
    [anon_sym_raw] = ACTIONS(69),
    [anon_sym_endraw] = ACTIONS(69),
    [anon_sym_macro] = ACTIONS(69),
    [anon_sym_endmacro] = ACTIONS(69),
    [anon_sym_extends] = ACTIONS(69),
    [anon_sym_block] = ACTIONS(69),
    [anon_sym_endblock] = ACTIONS(69),
    [anon_sym_call] = ACTIONS(69),
    [anon_sym_endcall] = ACTIONS(69),
    [anon_sym_filter] = ACTIONS(69),
    [anon_sym_endfilter] = ACTIONS(69),
    [anon_sym_set] = ACTIONS(69),
    [anon_sym_endset] = ACTIONS(69),
    [anon_sym_include] = ACTIONS(69),
    [anon_sym_import] = ACTIONS(69),
    [anon_sym_from] = ACTIONS(69),
    [anon_sym_autoescape] = ACTIONS(69),
    [anon_sym_endautoescape] = ACTIONS(69),
    [anon_sym_trans] = ACTIONS(69),
    [anon_sym_endtrans] = ACTIONS(69),
    [anon_sym_pluralize] = ACTIONS(69),
    [anon_sym_with] = ACTIONS(69),
    [anon_sym_endwith] = ACTIONS(69),
    [anon_sym_debug] = ACTIONS(69),
    [anon_sym_do] = ACTIONS(69),
    [anon_sym_is] = ACTIONS(69),
    [sym__white_space] = ACTIONS(71),
    [sym_operator] = ACTIONS(69),
    [sym_filter_operator] = ACTIONS(69),
    [sym_equal_operator] = ACTIONS(69),
    [sym_string] = ACTIONS(69),
  },
  [STATE(10)] = {
    [sym_identifier] = ACTIONS(48),
    [sym_statement_end] = ACTIONS(48),
    [anon_sym_LBRACE] = ACTIONS(48),
    [anon_sym_for] = ACTIONS(48),
    [anon_sym_in] = ACTIONS(48),
    [anon_sym_endfor] = ACTIONS(48),
    [anon_sym_if] = ACTIONS(48),
    [anon_sym_and] = ACTIONS(48),
    [anon_sym_or] = ACTIONS(48),
    [anon_sym_endif] = ACTIONS(48),
    [anon_sym_else] = ACTIONS(48),
    [anon_sym_elif] = ACTIONS(48),
    [anon_sym_raw] = ACTIONS(48),
    [anon_sym_endraw] = ACTIONS(48),
    [anon_sym_macro] = ACTIONS(48),
    [anon_sym_endmacro] = ACTIONS(48),
    [anon_sym_extends] = ACTIONS(48),
    [anon_sym_block] = ACTIONS(48),
    [anon_sym_endblock] = ACTIONS(48),
    [anon_sym_call] = ACTIONS(48),
    [anon_sym_endcall] = ACTIONS(48),
    [anon_sym_filter] = ACTIONS(48),
    [anon_sym_endfilter] = ACTIONS(48),
    [anon_sym_set] = ACTIONS(48),
    [anon_sym_endset] = ACTIONS(48),
    [anon_sym_include] = ACTIONS(48),
    [anon_sym_import] = ACTIONS(48),
    [anon_sym_from] = ACTIONS(48),
    [anon_sym_autoescape] = ACTIONS(48),
    [anon_sym_endautoescape] = ACTIONS(48),
    [anon_sym_trans] = ACTIONS(48),
    [anon_sym_endtrans] = ACTIONS(48),
    [anon_sym_pluralize] = ACTIONS(48),
    [anon_sym_with] = ACTIONS(48),
    [anon_sym_endwith] = ACTIONS(48),
    [anon_sym_debug] = ACTIONS(48),
    [anon_sym_do] = ACTIONS(48),
    [anon_sym_is] = ACTIONS(48),
    [sym__white_space] = ACTIONS(50),
    [sym_operator] = ACTIONS(48),
    [sym_filter_operator] = ACTIONS(48),
    [sym_equal_operator] = ACTIONS(48),
    [sym_string] = ACTIONS(48),
  },
  [STATE(11)] = {
    [sym_identifier] = ACTIONS(73),
    [sym_statement_end] = ACTIONS(73),
    [anon_sym_LBRACE] = ACTIONS(73),
    [anon_sym_for] = ACTIONS(73),
    [anon_sym_in] = ACTIONS(73),
    [anon_sym_endfor] = ACTIONS(73),
    [anon_sym_if] = ACTIONS(73),
    [anon_sym_and] = ACTIONS(73),
    [anon_sym_or] = ACTIONS(73),
    [anon_sym_endif] = ACTIONS(73),
    [anon_sym_else] = ACTIONS(73),
    [anon_sym_elif] = ACTIONS(73),
    [anon_sym_raw] = ACTIONS(73),
    [anon_sym_endraw] = ACTIONS(73),
    [anon_sym_macro] = ACTIONS(73),
    [anon_sym_endmacro] = ACTIONS(73),
    [anon_sym_extends] = ACTIONS(73),
    [anon_sym_block] = ACTIONS(73),
    [anon_sym_endblock] = ACTIONS(73),
    [anon_sym_call] = ACTIONS(73),
    [anon_sym_endcall] = ACTIONS(73),
    [anon_sym_filter] = ACTIONS(73),
    [anon_sym_endfilter] = ACTIONS(73),
    [anon_sym_set] = ACTIONS(73),
    [anon_sym_endset] = ACTIONS(73),
    [anon_sym_include] = ACTIONS(73),
    [anon_sym_import] = ACTIONS(73),
    [anon_sym_from] = ACTIONS(73),
    [anon_sym_autoescape] = ACTIONS(73),
    [anon_sym_endautoescape] = ACTIONS(73),
    [anon_sym_trans] = ACTIONS(73),
    [anon_sym_endtrans] = ACTIONS(73),
    [anon_sym_pluralize] = ACTIONS(73),
    [anon_sym_with] = ACTIONS(73),
    [anon_sym_endwith] = ACTIONS(73),
    [anon_sym_debug] = ACTIONS(73),
    [anon_sym_do] = ACTIONS(73),
    [anon_sym_is] = ACTIONS(73),
    [sym__white_space] = ACTIONS(75),
    [sym_operator] = ACTIONS(73),
    [sym_filter_operator] = ACTIONS(73),
    [sym_equal_operator] = ACTIONS(73),
    [sym_string] = ACTIONS(73),
  },
  [STATE(12)] = {
    [sym_identifier] = ACTIONS(77),
    [sym_statement_end] = ACTIONS(77),
    [anon_sym_LBRACE] = ACTIONS(77),
    [anon_sym_for] = ACTIONS(77),
    [anon_sym_in] = ACTIONS(77),
    [anon_sym_endfor] = ACTIONS(77),
    [anon_sym_if] = ACTIONS(77),
    [anon_sym_and] = ACTIONS(77),
    [anon_sym_or] = ACTIONS(77),
    [anon_sym_endif] = ACTIONS(77),
    [anon_sym_else] = ACTIONS(77),
    [anon_sym_elif] = ACTIONS(77),
    [anon_sym_raw] = ACTIONS(77),
    [anon_sym_endraw] = ACTIONS(77),
    [anon_sym_macro] = ACTIONS(77),
    [anon_sym_endmacro] = ACTIONS(77),
    [anon_sym_extends] = ACTIONS(77),
    [anon_sym_block] = ACTIONS(77),
    [anon_sym_endblock] = ACTIONS(77),
    [anon_sym_call] = ACTIONS(77),
    [anon_sym_endcall] = ACTIONS(77),
    [anon_sym_filter] = ACTIONS(77),
    [anon_sym_endfilter] = ACTIONS(77),
    [anon_sym_set] = ACTIONS(77),
    [anon_sym_endset] = ACTIONS(77),
    [anon_sym_include] = ACTIONS(77),
    [anon_sym_import] = ACTIONS(77),
    [anon_sym_from] = ACTIONS(77),
    [anon_sym_autoescape] = ACTIONS(77),
    [anon_sym_endautoescape] = ACTIONS(77),
    [anon_sym_trans] = ACTIONS(77),
    [anon_sym_endtrans] = ACTIONS(77),
    [anon_sym_pluralize] = ACTIONS(77),
    [anon_sym_with] = ACTIONS(77),
    [anon_sym_endwith] = ACTIONS(77),
    [anon_sym_debug] = ACTIONS(77),
    [anon_sym_do] = ACTIONS(77),
    [anon_sym_is] = ACTIONS(77),
    [sym__white_space] = ACTIONS(79),
    [sym_operator] = ACTIONS(77),
    [sym_filter_operator] = ACTIONS(77),
    [sym_equal_operator] = ACTIONS(77),
    [sym_string] = ACTIONS(77),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(19), 1,
      anon_sym_in,
    STATE(2), 1,
      sym_keyword,
    ACTIONS(81), 34,
      anon_sym_for,
      anon_sym_endfor,
      anon_sym_if,
      anon_sym_and,
      anon_sym_or,
      anon_sym_endif,
      anon_sym_else,
      anon_sym_elif,
      anon_sym_raw,
      anon_sym_endraw,
      anon_sym_macro,
      anon_sym_endmacro,
      anon_sym_extends,
      anon_sym_block,
      anon_sym_endblock,
      anon_sym_call,
      anon_sym_endcall,
      anon_sym_filter,
      anon_sym_endfilter,
      anon_sym_set,
      anon_sym_endset,
      anon_sym_include,
      anon_sym_import,
      anon_sym_from,
      anon_sym_autoescape,
      anon_sym_endautoescape,
      anon_sym_trans,
      anon_sym_endtrans,
      anon_sym_pluralize,
      anon_sym_with,
      anon_sym_endwith,
      anon_sym_debug,
      anon_sym_do,
      anon_sym_is,
  [43] = 6,
    ACTIONS(83), 1,
      ts_builtin_sym_end,
    ACTIONS(88), 1,
      sym_statement_begin,
    ACTIONS(91), 1,
      sym_expression_begin,
    ACTIONS(94), 1,
      anon_sym_LBRACE_POUND,
    ACTIONS(85), 5,
      aux_sym__text_token1,
      aux_sym__not_token1,
      aux_sym__not_token2,
      aux_sym__not_token3,
      aux_sym__not_token4,
    STATE(14), 7,
      sym__text,
      sym__not,
      sym__node,
      sym_statement,
      sym_expression,
      sym_comment,
      aux_sym_source_file_repeat1,
  [72] = 6,
    ACTIONS(7), 1,
      sym_statement_begin,
    ACTIONS(9), 1,
      sym_expression_begin,
    ACTIONS(11), 1,
      anon_sym_LBRACE_POUND,
    ACTIONS(97), 1,
      ts_builtin_sym_end,
    ACTIONS(99), 5,
      aux_sym__text_token1,
      aux_sym__not_token1,
      aux_sym__not_token2,
      aux_sym__not_token3,
      aux_sym__not_token4,
    STATE(14), 7,
      sym__text,
      sym__not,
      sym__node,
      sym_statement,
      sym_expression,
      sym_comment,
      aux_sym_source_file_repeat1,
  [101] = 9,
    ACTIONS(101), 1,
      sym_identifier,
    ACTIONS(103), 1,
      anon_sym_LBRACE,
    ACTIONS(105), 1,
      anon_sym_RBRACE,
    ACTIONS(107), 1,
      sym__white_space,
    STATE(21), 1,
      sym__map_begin,
    STATE(39), 1,
      sym_dotted_identifier,
    STATE(40), 1,
      sym__map_end,
    STATE(17), 2,
      sym_map,
      aux_sym__inner_text2,
    ACTIONS(109), 4,
      sym_operator,
      sym_filter_operator,
      sym_equal_operator,
      sym_string,
  [133] = 9,
    ACTIONS(101), 1,
      sym_identifier,
    ACTIONS(103), 1,
      anon_sym_LBRACE,
    ACTIONS(111), 1,
      anon_sym_RBRACE,
    ACTIONS(113), 1,
      sym__white_space,
    STATE(21), 1,
      sym__map_begin,
    STATE(39), 1,
      sym_dotted_identifier,
    STATE(44), 1,
      sym__map_end,
    STATE(25), 2,
      sym_map,
      aux_sym__inner_text2,
    ACTIONS(115), 4,
      sym_operator,
      sym_filter_operator,
      sym_equal_operator,
      sym_string,
  [165] = 9,
    ACTIONS(101), 1,
      sym_identifier,
    ACTIONS(103), 1,
      anon_sym_LBRACE,
    ACTIONS(113), 1,
      sym__white_space,
    ACTIONS(117), 1,
      anon_sym_RBRACE,
    STATE(11), 1,
      sym__map_end,
    STATE(21), 1,
      sym__map_begin,
    STATE(39), 1,
      sym_dotted_identifier,
    STATE(25), 2,
      sym_map,
      aux_sym__inner_text2,
    ACTIONS(115), 4,
      sym_operator,
      sym_filter_operator,
      sym_equal_operator,
      sym_string,
  [197] = 9,
    ACTIONS(101), 1,
      sym_identifier,
    ACTIONS(103), 1,
      anon_sym_LBRACE,
    ACTIONS(113), 1,
      sym__white_space,
    ACTIONS(119), 1,
      anon_sym_RBRACE,
    STATE(21), 1,
      sym__map_begin,
    STATE(39), 1,
      sym_dotted_identifier,
    STATE(43), 1,
      sym__map_end,
    STATE(25), 2,
      sym_map,
      aux_sym__inner_text2,
    ACTIONS(115), 4,
      sym_operator,
      sym_filter_operator,
      sym_equal_operator,
      sym_string,
  [229] = 9,
    ACTIONS(101), 1,
      sym_identifier,
    ACTIONS(103), 1,
      anon_sym_LBRACE,
    ACTIONS(121), 1,
      anon_sym_RBRACE,
    ACTIONS(123), 1,
      sym__white_space,
    STATE(12), 1,
      sym__map_end,
    STATE(21), 1,
      sym__map_begin,
    STATE(39), 1,
      sym_dotted_identifier,
    STATE(18), 2,
      sym_map,
      aux_sym__inner_text2,
    ACTIONS(125), 4,
      sym_operator,
      sym_filter_operator,
      sym_equal_operator,
      sym_string,
  [261] = 9,
    ACTIONS(101), 1,
      sym_identifier,
    ACTIONS(103), 1,
      anon_sym_LBRACE,
    ACTIONS(127), 1,
      anon_sym_RBRACE,
    ACTIONS(129), 1,
      sym__white_space,
    STATE(21), 1,
      sym__map_begin,
    STATE(39), 1,
      sym_dotted_identifier,
    STATE(41), 1,
      sym__map_end,
    STATE(19), 2,
      sym_map,
      aux_sym__inner_text2,
    ACTIONS(131), 4,
      sym_operator,
      sym_filter_operator,
      sym_equal_operator,
      sym_string,
  [293] = 8,
    ACTIONS(133), 1,
      sym_identifier,
    ACTIONS(135), 1,
      sym_expression_end,
    ACTIONS(137), 1,
      anon_sym_LBRACE,
    ACTIONS(139), 1,
      sym__white_space,
    STATE(16), 1,
      sym__map_begin,
    STATE(42), 1,
      sym_dotted_identifier,
    STATE(23), 2,
      sym_map,
      aux_sym__inner_text2,
    ACTIONS(141), 4,
      sym_operator,
      sym_filter_operator,
      sym_equal_operator,
      sym_string,
  [322] = 8,
    ACTIONS(133), 1,
      sym_identifier,
    ACTIONS(137), 1,
      anon_sym_LBRACE,
    ACTIONS(143), 1,
      sym_expression_end,
    ACTIONS(145), 1,
      sym__white_space,
    STATE(16), 1,
      sym__map_begin,
    STATE(42), 1,
      sym_dotted_identifier,
    STATE(24), 2,
      sym_map,
      aux_sym__inner_text2,
    ACTIONS(147), 4,
      sym_operator,
      sym_filter_operator,
      sym_equal_operator,
      sym_string,
  [351] = 8,
    ACTIONS(149), 1,
      sym_identifier,
    ACTIONS(152), 1,
      sym_expression_end,
    ACTIONS(154), 1,
      anon_sym_LBRACE,
    ACTIONS(157), 1,
      sym__white_space,
    STATE(16), 1,
      sym__map_begin,
    STATE(42), 1,
      sym_dotted_identifier,
    STATE(24), 2,
      sym_map,
      aux_sym__inner_text2,
    ACTIONS(160), 4,
      sym_operator,
      sym_filter_operator,
      sym_equal_operator,
      sym_string,
  [380] = 8,
    ACTIONS(152), 1,
      anon_sym_RBRACE,
    ACTIONS(163), 1,
      sym_identifier,
    ACTIONS(166), 1,
      anon_sym_LBRACE,
    ACTIONS(169), 1,
      sym__white_space,
    STATE(21), 1,
      sym__map_begin,
    STATE(39), 1,
      sym_dotted_identifier,
    STATE(25), 2,
      sym_map,
      aux_sym__inner_text2,
    ACTIONS(172), 4,
      sym_operator,
      sym_filter_operator,
      sym_equal_operator,
      sym_string,
  [409] = 4,
    ACTIONS(177), 1,
      sym__white_space,
    ACTIONS(179), 1,
      anon_sym_DOT,
    STATE(27), 1,
      aux_sym_dotted_identifier_repeat1,
    ACTIONS(175), 7,
      sym_expression_end,
      anon_sym_LBRACE,
      sym_identifier,
      sym_operator,
      sym_filter_operator,
      sym_equal_operator,
      sym_string,
  [428] = 4,
    ACTIONS(56), 1,
      sym__white_space,
    ACTIONS(179), 1,
      anon_sym_DOT,
    STATE(28), 1,
      aux_sym_dotted_identifier_repeat1,
    ACTIONS(54), 7,
      sym_expression_end,
      anon_sym_LBRACE,
      sym_identifier,
      sym_operator,
      sym_filter_operator,
      sym_equal_operator,
      sym_string,
  [447] = 4,
    ACTIONS(60), 1,
      sym__white_space,
    ACTIONS(181), 1,
      anon_sym_DOT,
    STATE(28), 1,
      aux_sym_dotted_identifier_repeat1,
    ACTIONS(58), 7,
      sym_expression_end,
      anon_sym_LBRACE,
      sym_identifier,
      sym_operator,
      sym_filter_operator,
      sym_equal_operator,
      sym_string,
  [466] = 4,
    ACTIONS(177), 1,
      sym__white_space,
    ACTIONS(184), 1,
      anon_sym_DOT,
    STATE(30), 1,
      aux_sym_dotted_identifier_repeat1,
    ACTIONS(175), 7,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_identifier,
      sym_operator,
      sym_filter_operator,
      sym_equal_operator,
      sym_string,
  [485] = 4,
    ACTIONS(56), 1,
      sym__white_space,
    ACTIONS(184), 1,
      anon_sym_DOT,
    STATE(31), 1,
      aux_sym_dotted_identifier_repeat1,
    ACTIONS(54), 7,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_identifier,
      sym_operator,
      sym_filter_operator,
      sym_equal_operator,
      sym_string,
  [504] = 4,
    ACTIONS(60), 1,
      sym__white_space,
    ACTIONS(186), 1,
      anon_sym_DOT,
    STATE(31), 1,
      aux_sym_dotted_identifier_repeat1,
    ACTIONS(58), 7,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_identifier,
      sym_operator,
      sym_filter_operator,
      sym_equal_operator,
      sym_string,
  [523] = 2,
    ACTIONS(189), 1,
      ts_builtin_sym_end,
    ACTIONS(191), 8,
      aux_sym__text_token1,
      aux_sym__not_token1,
      aux_sym__not_token2,
      aux_sym__not_token3,
      aux_sym__not_token4,
      sym_statement_begin,
      sym_expression_begin,
      anon_sym_LBRACE_POUND,
  [537] = 2,
    ACTIONS(193), 1,
      ts_builtin_sym_end,
    ACTIONS(195), 8,
      aux_sym__text_token1,
      aux_sym__not_token1,
      aux_sym__not_token2,
      aux_sym__not_token3,
      aux_sym__not_token4,
      sym_statement_begin,
      sym_expression_begin,
      anon_sym_LBRACE_POUND,
  [551] = 2,
    ACTIONS(197), 1,
      ts_builtin_sym_end,
    ACTIONS(199), 8,
      aux_sym__text_token1,
      aux_sym__not_token1,
      aux_sym__not_token2,
      aux_sym__not_token3,
      aux_sym__not_token4,
      sym_statement_begin,
      sym_expression_begin,
      anon_sym_LBRACE_POUND,
  [565] = 2,
    ACTIONS(201), 1,
      ts_builtin_sym_end,
    ACTIONS(203), 8,
      aux_sym__text_token1,
      aux_sym__not_token1,
      aux_sym__not_token2,
      aux_sym__not_token3,
      aux_sym__not_token4,
      sym_statement_begin,
      sym_expression_begin,
      anon_sym_LBRACE_POUND,
  [579] = 2,
    ACTIONS(205), 1,
      ts_builtin_sym_end,
    ACTIONS(207), 8,
      aux_sym__text_token1,
      aux_sym__not_token1,
      aux_sym__not_token2,
      aux_sym__not_token3,
      aux_sym__not_token4,
      sym_statement_begin,
      sym_expression_begin,
      anon_sym_LBRACE_POUND,
  [593] = 2,
    ACTIONS(67), 1,
      sym__white_space,
    ACTIONS(65), 8,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOT,
      sym_identifier,
      sym_operator,
      sym_filter_operator,
      sym_equal_operator,
      sym_string,
  [607] = 2,
    ACTIONS(67), 1,
      sym__white_space,
    ACTIONS(65), 8,
      sym_expression_end,
      anon_sym_LBRACE,
      anon_sym_DOT,
      sym_identifier,
      sym_operator,
      sym_filter_operator,
      sym_equal_operator,
      sym_string,
  [621] = 2,
    ACTIONS(177), 1,
      sym__white_space,
    ACTIONS(175), 7,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_identifier,
      sym_operator,
      sym_filter_operator,
      sym_equal_operator,
      sym_string,
  [634] = 2,
    ACTIONS(79), 1,
      sym__white_space,
    ACTIONS(77), 7,
      sym_expression_end,
      anon_sym_LBRACE,
      sym_identifier,
      sym_operator,
      sym_filter_operator,
      sym_equal_operator,
      sym_string,
  [647] = 2,
    ACTIONS(79), 1,
      sym__white_space,
    ACTIONS(77), 7,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_identifier,
      sym_operator,
      sym_filter_operator,
      sym_equal_operator,
      sym_string,
  [660] = 2,
    ACTIONS(177), 1,
      sym__white_space,
    ACTIONS(175), 7,
      sym_expression_end,
      anon_sym_LBRACE,
      sym_identifier,
      sym_operator,
      sym_filter_operator,
      sym_equal_operator,
      sym_string,
  [673] = 2,
    ACTIONS(75), 1,
      sym__white_space,
    ACTIONS(73), 7,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_identifier,
      sym_operator,
      sym_filter_operator,
      sym_equal_operator,
      sym_string,
  [686] = 2,
    ACTIONS(75), 1,
      sym__white_space,
    ACTIONS(73), 7,
      sym_expression_end,
      anon_sym_LBRACE,
      sym_identifier,
      sym_operator,
      sym_filter_operator,
      sym_equal_operator,
      sym_string,
  [699] = 1,
    ACTIONS(209), 1,
      aux_sym_comment_token1,
  [703] = 1,
    ACTIONS(211), 1,
      anon_sym_POUND_RBRACE,
  [707] = 1,
    ACTIONS(213), 1,
      ts_builtin_sym_end,
  [711] = 1,
    ACTIONS(215), 1,
      sym_identifier,
  [715] = 1,
    ACTIONS(217), 1,
      sym_identifier,
  [719] = 1,
    ACTIONS(219), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(13)] = 0,
  [SMALL_STATE(14)] = 43,
  [SMALL_STATE(15)] = 72,
  [SMALL_STATE(16)] = 101,
  [SMALL_STATE(17)] = 133,
  [SMALL_STATE(18)] = 165,
  [SMALL_STATE(19)] = 197,
  [SMALL_STATE(20)] = 229,
  [SMALL_STATE(21)] = 261,
  [SMALL_STATE(22)] = 293,
  [SMALL_STATE(23)] = 322,
  [SMALL_STATE(24)] = 351,
  [SMALL_STATE(25)] = 380,
  [SMALL_STATE(26)] = 409,
  [SMALL_STATE(27)] = 428,
  [SMALL_STATE(28)] = 447,
  [SMALL_STATE(29)] = 466,
  [SMALL_STATE(30)] = 485,
  [SMALL_STATE(31)] = 504,
  [SMALL_STATE(32)] = 523,
  [SMALL_STATE(33)] = 537,
  [SMALL_STATE(34)] = 551,
  [SMALL_STATE(35)] = 565,
  [SMALL_STATE(36)] = 579,
  [SMALL_STATE(37)] = 593,
  [SMALL_STATE(38)] = 607,
  [SMALL_STATE(39)] = 621,
  [SMALL_STATE(40)] = 634,
  [SMALL_STATE(41)] = 647,
  [SMALL_STATE(42)] = 660,
  [SMALL_STATE(43)] = 673,
  [SMALL_STATE(44)] = 686,
  [SMALL_STATE(45)] = 699,
  [SMALL_STATE(46)] = 703,
  [SMALL_STATE(47)] = 707,
  [SMALL_STATE(48)] = 711,
  [SMALL_STATE(49)] = 715,
  [SMALL_STATE(50)] = 719,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__inner_text, 2, 0, 4), SHIFT_REPEAT(5),
  [34] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__inner_text, 2, 0, 4),
  [36] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__inner_text, 2, 0, 4), SHIFT_REPEAT(20),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__inner_text, 2, 0, 4), SHIFT_REPEAT(9),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__inner_text, 2, 0, 4), SHIFT_REPEAT(4),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__inner_text, 2, 0, 4), SHIFT_REPEAT(4),
  [48] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__inner_text, 1, 0, 1),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__inner_text, 1, 0, 1),
  [52] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [54] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dotted_identifier, 2, 0, 2),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dotted_identifier, 2, 0, 2),
  [58] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_dotted_identifier_repeat1, 2, 0, 7),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_dotted_identifier_repeat1, 2, 0, 7),
  [62] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_dotted_identifier_repeat1, 2, 0, 7), SHIFT_REPEAT(48),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_dotted_identifier_repeat1, 2, 0, 6),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_dotted_identifier_repeat1, 2, 0, 6),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_keyword, 1, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_keyword, 1, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_map, 3, 0, 3),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map, 3, 0, 3),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_map, 2, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map, 2, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [85] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [88] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [91] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [94] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [101] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [103] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [105] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [109] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [111] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [115] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [117] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [119] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [121] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [125] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [127] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [131] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [133] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [135] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [137] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [141] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [143] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [147] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [149] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__inner_text2, 2, 0, 4), SHIFT_REPEAT(26),
  [152] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__inner_text2, 2, 0, 4),
  [154] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__inner_text2, 2, 0, 4), SHIFT_REPEAT(16),
  [157] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__inner_text2, 2, 0, 4), SHIFT_REPEAT(24),
  [160] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__inner_text2, 2, 0, 4), SHIFT_REPEAT(24),
  [163] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__inner_text2, 2, 0, 4), SHIFT_REPEAT(29),
  [166] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__inner_text2, 2, 0, 4), SHIFT_REPEAT(21),
  [169] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__inner_text2, 2, 0, 4), SHIFT_REPEAT(25),
  [172] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__inner_text2, 2, 0, 4), SHIFT_REPEAT(25),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__inner_text2, 1, 0, 1),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__inner_text2, 1, 0, 1),
  [179] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [181] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_dotted_identifier_repeat1, 2, 0, 7), SHIFT_REPEAT(49),
  [184] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [186] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_dotted_identifier_repeat1, 2, 0, 7), SHIFT_REPEAT(50),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 3, 0, 3),
  [191] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 3, 0, 3),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 3, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 3, 0, 0),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 4, 0, 5),
  [199] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 4, 0, 5),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3, 0, 0),
  [203] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 3, 0, 0),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 2, 0, 0),
  [207] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 2, 0, 0),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [213] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_jinja2(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "jinja2",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 16,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
